### PR TITLE
 Allow bulk removal of stashes #275 

### PR DESCRIPTION
**Pull request by grantholly**
https://github.com/sensu/uchiwa/issues/275

This pull request adds the ability to remove single, multiple, or all stashes.  The original functionality has been preserved in that you can still remove a stash by clicking the 'x' icon.  The clear stashes action has been put into the actions drop down menu and its own directive to follow the current UI.  For people using uchiwa in very large environments, it is helpful to search for a group of stashes and be able to remove them in bulk in a similar fashion to you might do that currently with events.

screen shot 2015-09-08 at 11 57 56 am

### CODE REVIEW

**Comment by jbehrends** [comment]
+1

**Comment by alanlaird** [comment]
+1

**Comment by oneeyedziggy** [comment]
+1

**Comment by togdon** [comment]
+1

**Comment by jbehrends** [comment]
@palourde Any chance we can get this feature merged?  Not having this has been a pain point in our environment from time to time.


Thanks!

**Comment by palourde** [comment]
This PR has been merged and the commits squashed into https://github.com/sensu/uchiwa-web/commit/e546f0ea3ab2f82f6e41e8ca79c095fc5843417f. Thanks a lot @grantholly!

**Pull request closed without merging**
