### PR TITLE
Grouped "Clients" page by subscriptions

### PR DESCRIPTION
**Pull request by traviswdev**
This is my attempt to clean up the clients page. Having to click around and apply filters or type in search boxes wasn't sufficient for my management, so they asked me to group clients.

Users can now view the status of entire subscription groups rather than (only) individual clients. If one of the machines in the group has a problem, the group will show up as having a problem. 

Now you can see the overall status of a product at a glance, and not have to filter or search for the machines in question. Simply clicking on the name of the subscription group will fold/unfold the groups so you can see which machines have a problem and what that problem is.

This is useful if you have a product you are monitoring that spans multiple machines (such as having a database on one machine and a web server on another, for example). All management has to do to check the status of a product is click the bookmark link to the groups page. If product-XYZ has something wrong with it, they don't have to see the machine or the problem, they can just call whoever needs to fix it. 

It is hard for me to imagine a reason that people wouldn't like this feature, but it may need to be modified further before it is ready to be commited to the master. 

In a feature request discussion, palourde mentioned perhaps putting this in another view. I was thinking  a checkbox in the settings menu that says "Group the Clients page by subcriptions" might also work...  in case people don't want this feature they can toggle it. 

I am submitting the work I have done thus far to get some input and thoughts from the other developers and community. I am not an experienced web developer, so the way I did things might not have been the most perfect or clean (although I think I did a pretty good job...).

I would be happy to get input or development from others.

### CODE REVIEW

**Comment by traviswdev** [comment]
Okay, here we go:
* I updated my uchiwa to the latest version that adds support for sensu enterprise dashboard and status filtering (hence a lot of the differences between files)
* I returned the clients page to the way it was
* I copy/pasted the "Clients" section from controllers.js to a new "Groups" section in the same file, updated the page header text, and added the functions needed to get the groups page to behave correctly
* I added "groups.html" in bower_components/uchiwa-web/partials/views
* I added a new icon in the sidebar for the groups page and linked to groups.html
* I changed app.js so the above link would resolve correctly
* I even added fancy +/- icons into the accordion to make it more obvious that the sections are expandible/collapsible

screen shot 2015-08-04 at 2 06 21 pm

screen shot 2015-08-04 at 2 06 33 pm

**Comment by traviswdev** [comment]
The last update I did changed the tooltip of the sidebar groups icon to show the number of **groups** with critical/warning/unknown statuses instead of number of clients. 

For example, if you have one client with a critical status and that client is in two groups, the groups tooltip will show "Critical: 2". 

I had previously just copy/pasted the clients tooltip and this was bothering me. The code I wrote works perfectly but might not be super-pretty-angular-style, if someone with higher web development knowledge wants to refactor it.

**Comment by tocomo** [comment]
You should think about fixing html comments '<! --' to '<!--'. btw: great work.

**Comment by pauloconnor** [comment]
Looks interesting, but it appears that you have partials as a subdirectory of itself. Might be worth rebasing against master also.

**Comment by palourde** [comment]
That's nice!

As mentioned before, maybe look at the partials folder and re-generate the CSS files with `grunt sass`.

**Comment by traviswdev** [comment]
This submission has been moved to pauloconnor's "Grouping clean up" mentioned directly above.

**Comment by zbintliff** [comment]
This is exactly what we were looking for but instead of grouping by 'subscriptions' grouping by some client defined key. For example if there was a `host_group` array/key in the client hash.  At our org all the teams use the same base subscription (check_http, check_port, check_process) and pass in data that is interpolated on the client.

Would it be possible to extend it to that? Or is that a very different PR?

**Comment by traviswdev** [comment]
Try asking in #80. The person who has the power to merge this hasn't had time to refactor it, maybe they could modify it in the process.

**Comment by thebenwaters** [comment]
+1

**Comment by sureshsubramaniam** [comment]
+1

**Comment by GuitarrasDeAmor** [comment]
Definitely like this idea - hoping it gets refactored/merged soon.

**Comment by pauloconnor** [comment]
@traviswdev should this PR be closed in favour of #80 so comments aren't split across both?

**Comment by traviswdev** [comment]
Good point. Closing PR. Comments should be posted on #80.

**Pull request closed without merging**
