### PR TITLE
Shorten long URLs in the client view

### PR DESCRIPTION
**Pull request by palourde**
Fixes https://github.com/sensu/uchiwa/issues/629

### CODE REVIEW

**Comment by palourde** [comment]
Example:
screen shot 2017-04-13 at 11 28 37

**Comment by jothoma1** [comment]
Thanks a lot !! Can you explain how to do it ? i have updated uchiwa to 0.24 but i still have the long URL ?

**Comment by palourde** [comment]
@jothoma1 Make sure to clear your browser cache if you were running an old Uchiwa version. If you still have this issue, could you take a screenshot?

Thanks

**Comment by exeral** [comment]
as you can see there is a huge bottom scrollbar for the long url

uchiwaurl
uchiwa024

cache was cleared of course.
Chrome Version 58.0.3029.81 (64-bit)

**Comment by jothoma1** [comment]
@palourde Thanks! for me, it was just a pb of cache :)

**Pull request merged**
