### PR TITLE
Hide 'Issue Request' button for standalone checks

### PR DESCRIPTION
**Pull request by palourde**
Closes https://github.com/sensu/uchiwa/issues/754

### CODE REVIEW

**Comment by peterhoeg** [comment]
It looks like this PR also removed the possibility to issue checks when looking at a client.

Before (with 1.1.2 and latest Sensu) it was possible to go to a client and then select a check and have the option to issue a check in addition to just going to the checks and issue checks from there.

With 1.2.0 the former is no longer possible while it can be done from the checks list.

We have no standalone checks so it cannot be that.

**Comment by jwatroba** [comment]
Yeah, this completely removed the 'Issue  Request' button from our non standalone checks as well.

**Comment by palourde** [comment]
I opened a new issue in order to track this bug: https://github.com/sensu/uchiwa/issues/778.

Thanks!

**Comment by jwatroba** [comment]
I just updated to the latest version - 1.3.0 and the 'issue request' button is still missing for our non-standalone checks.

**Comment by kchenowe** [comment]
What version of uchiwa should I use to restore the "issue request" button back to uchiwa?

Thanks!

**Comment by peterhoeg** [comment]
1.1.2 is the one you are looking for.

**Comment by jwatroba** [comment]
Did this button ever make it back in? We're running 1.5.0 and this button is still missing.
Thanks.

**Comment by peterhoeg** [comment]
Nope, see https://github.com/sensu/uchiwa/issues/778

**Pull request merged**
