### PR TITLE
Select distinct checks (with check count) in events

### PR DESCRIPTION
**Pull request by pauloconnor**
This allows you to see how many checks are alerting, but also allows you to select checks individually without searching for them.

screen shot 2015-05-10 at 1 45 00 pm

### CODE REVIEW

**Comment by palourde** [comment]
@pauloconnor It all looks great however I'm facing a little bug. When I'm trying to *select all* events using the select box in the table header, none of them are getting selected:

screen shot 2015-05-12 at 16 34 02

Maybe it's an issue with the rebase I made, can you confirm?

**Comment by pauloconnor** [comment]
Ah, well caught. There was a typo where I was comparing check against dc. Bad copy/paste.

**Comment by pauloconnor** [comment]
@palourde is there anything else needed for this PR? I'd love to get this deployed.

**Comment by palourde** [comment]
@pauloconnor Really sorry about the delay, I didn't had a lot of free time in the last few days. I'll get on it today.

**Pull request merged**
