### PR TITLE
Grouping clean up

### PR DESCRIPTION
**Pull request by pauloconnor**
This is based entirely on @traviswdev's work in https://github.com/sensu/uchiwa-web/pull/60, just cleaned up and brought up to date with Master. I _think_ it works, but since we don't use subscriptions, I don't have a decent testbed for it.

### CODE REVIEW

**Comment by traviswdev** [comment]
Thanks for cleaning this up! I was just thinking about it yesterday. I have changed positions since working on this last and haven't had time to polish it up.

**Comment by palourde** [comment]
Thanks @pauloconnor!

I had very limited time to work on Uchiwa during the past few weeks. I hope to be able to take a look at it this weekend.

**Comment by traviswdev** [comment]
How's this looking? Planning on merging this with the master?

**Comment by hany** [comment]
:+1: this looks great! Any word on merging?

**Comment by traviswdev** [comment]
Every once in a while this project pops back into my head and I come on to see if any progress has been made... 
Looks like @pauloconnor's fixes/cleanups are still passing checks and can be merged. 

@palourde, can you check it out and see what you think? Screenshots and description at #60.

**Comment by artkrz** [comment]
Tests passed, no conflicts. Why's no one merging this ?

**Comment by palourde** [comment]
The way we use the Angular `ng-repeat` feature has been modified for performance reasons so I still have to do some refactoring on this PR and I simply didn't had time yet.

**Comment by zbintliff** [comment]
This is exactly what we were looking for but instead of grouping by 'subscriptions' grouping by some client defined key. For example if there was a host_group array/key in the client hash. At our org all the teams use the same base subscription (check_http, check_port, check_process) and pass in data that is interpolated on the client.

Would it be possible to extend it to that? Or is that a very different PR?

**Comment by thebenwaters** [comment]
+1

**Comment by sureshsubramaniam** [comment]
+1

**Comment by pauloconnor** [comment]
I've reworked this branch to remove the Groups tab, and instead add a grouping filter to the Events page (and soon the Clients page).

This should be considered a WIP, and it is quite slow due to ng-repeat really not liking multiple ng-repeats being on a page.

Additionally, this pulls from a client hash called "Tags". Any field in the tag will be populated into the Grouping dropdown, and the events will then be grouped under each tag. For example, I could use "Host Purpose" and have Webs, DBs, File Servers etc.

**Comment by GuitarrasDeAmor** [comment]
Is there any info on when/if this will be merged? This is a feature my team is very interested in, and seems like a great addition to Uchiwa in general. I wish I had enough knowledge to help with any refactoring/conflicts.

**Comment by pmaluf** [comment]
+1

**Comment by akulakhan** [comment]
+1

**Comment by lisfo4ka** [comment]
+1

**Comment by pauloconnor** [comment]
I fear that the longer I leave this PR open, the more bit rot will happen, and the less chance that it will ever get merged. An 18 month old PR with no real feedback from the upstream owners as to why it hasn't been merged is super disappointing.

**Comment by hany** [comment]
That's very disappointing. Been watching this PR for a while.

**Pull request closed without merging**
